/*
    Observable.forkJoin([
      characterDesignService.preloadCommons(),
      fileService.preloadCommons(),
      roomDesignService.preloadCommons(),
      shipDesignService.preloadCommons(),
      spriteService.preloadCommons()
    ])
    .subscribe();
*/